language: perl
perl:
  - "5.30"
env:
  - AUTHOR_TESTING=1 RELEASE_TESTING=1 PERL_CPANM_OPT="--quiet --notest"
cache:
  directories:
    - ${PERLBREW_ROOT}/perls/${PERLBREW_PERL}/lib
    - ${PERLBREW_ROOT}/perls/${PERLBREW_PERL}/bin
before_install:
  - cpanm Perl::Critic
  - perlcritic --quiet --single-policy=RequireTidyCode bin
  - dzil authordeps --missing | cpanm
  - dzil listdeps --author --missing | cpanm
  - cpanm DBI IPC::Shareable Parallel::ForkManager Digest::HMAC_SHA1
  - cpanm String::Escape XML::LibXML Net::SFTP::Foreign IO::Pty Test::mysqld
install:
  - dzil build --in build --notgz
script:
  - cd build && prove --timer --lib --recurse --jobs $(nproc) --shuffle t/
