---
labels: 'triage needed'
body:
    - type: textarea
      attributes:
          label: Describe your experience
          description: A clear and concise description of the observed behavior.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Expected behavior
          description: A clear and concise description of the expected behavior.
      validations:
          required: true
    - type: textarea
      attributes:
          label: How to reproduce it
          description: Steps to reproduce the unexpected behavior.
          placeholder: |
              1. Do this.
              2. Then do that.
              3. Observe the issue.
      validations:
          required: true
    - type: textarea
      attributes:
          label: Code example
          description: Shortest code example that demonstrates the issue, like a Rexfile with a single task.
          placeholder: |
              ```perl

              ```
    - type: textarea
      attributes:
          label: Additional context
          description: Share debug logs after running your code with `rex -d`, and [attach the output as a file](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests). Remove any sensitive information before posting. If you choose to copy-paste, make sure to post as a code block instead of text.
    - type: markdown
      attributes:
          value: '## Circumstances'
    - type: input
      attributes:
          label: Rex version
          description: Obtain it with `rex -v`.
      validations:
          required: true
    - type: dropdown
      attributes:
          label: Installation method
          options:
              - package manager
              - cpan client
              - dzil install
              - other (please describe above)
      validations:
          required: true
    - type: input
      attributes:
          label: Perl version
          description: Obtain with `perl -v`.
      validations:
          required: true
    - type: input
      attributes:
          label: Operating system running rex
          description: As specifically as possible.
      validations:
          required: true
    - type: input
      attributes:
          label: Operating system managed by rex
          description: Even if it is the local machine.
          placeholder: local
      validations:
          required: true
