---
name: lint commit messages

on:
  pull_request:
  workflow_dispatch:

jobs:
  commitlint:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .github/workflows/config/commitlint.config.js
          firstParent: true
